use crate::datatypes::DataType;

/// Access type for an OD entry.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum AccessType {
    Ro,
    Wo,
    Rw,
    Const,
}

/// CANopen object type.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ObjectType {
    Var,
    Array,
    Record,
}

/// Static metadata for an OD entry (typically generated by proc macro, lives in flash).
#[derive(Clone, Copy, Debug)]
pub struct OdEntryMeta {
    pub index: u16,
    pub subindex: u8,
    pub data_type: DataType,
    pub access: AccessType,
    pub pdo_mappable: bool,
    pub name: &'static str,
    /// Maximum size in bytes for variable-length types. None for fixed-size types.
    pub max_size: Option<u16>,
}

/// Errors from OD operations.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum OdError {
    NotFound,
    ReadOnly,
    WriteOnly,
    DataTypeMismatch,
    ValueTooLong,
    ValueRange,
    HardwareError,
}

/// Emitted when the protocol stack modifies an OD entry.
#[derive(Clone, Copy, Debug)]
pub struct OdEvent {
    pub index: u16,
    pub subindex: u8,
    pub source: OdEventSource,
}

/// Source of an OD modification event.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum OdEventSource {
    /// Remote SDO download wrote this entry.
    Sdo,
    /// Incoming RPDO mapped to this entry.
    Rpdo,
}

/// Signal type for async notification of OD events.
///
/// Place in a `static` and pass to [`Node::set_event_signal`]. An async task
/// can `signal.wait().await` to be woken when the protocol stack modifies an
/// OD entry (SDO download or RPDO write).
#[cfg(feature = "embassy")]
pub type OdEventSignal =
    embassy_sync::signal::Signal<embassy_sync::blocking_mutex::raw::CriticalSectionRawMutex, ()>;

/// Trait for an object dictionary. Implemented by proc-macro-generated structs.
///
/// All read/write operations use byte slices for transport-level generality.
/// The generated struct provides typed accessor methods for application code.
pub trait ObjectDictionary {
    /// Look up entry metadata by index and subindex.
    fn lookup(&self, index: u16, subindex: u8) -> Option<&'static OdEntryMeta>;

    /// Read a value from the OD into `buf`. Returns the number of bytes written.
    fn read(&self, index: u16, subindex: u8, buf: &mut [u8]) -> Result<usize, OdError>;

    /// Write a value to the OD from `data`.
    fn write(&mut self, index: u16, subindex: u8, data: &[u8]) -> Result<(), OdError>;

    /// Number of subindices for a given index (sub0 value for arrays/records).
    fn sub_count(&self, index: u16) -> Option<u8>;

    /// Validate a write before it is committed to the OD.
    ///
    /// Called by the SDO server before `write()`. If this returns `Err`, the
    /// SDO server sends an abort and the write is not applied. Override this
    /// to implement application-level validation (e.g., range checks, state
    /// guards, cross-field constraints).
    ///
    /// The default implementation accepts all writes.
    ///
    /// Common return errors:
    /// - `OdError::ValueRange` — value out of application-defined range
    /// - `OdError::HardwareError` — device not ready (e.g., flash in error state)
    fn validate_write(&self, _index: u16, _subindex: u8, _data: &[u8]) -> Result<(), OdError> {
        Ok(())
    }
}
