use crate::datatypes::DataType;

/// Access type for an OD entry.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum AccessType {
    Ro,
    Wo,
    Rw,
    Const,
}

/// CANopen object type.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum ObjectType {
    Var,
    Array,
    Record,
}

/// Static metadata for an OD entry (typically generated by proc macro, lives in flash).
#[derive(Clone, Copy, Debug)]
pub struct OdEntryMeta {
    pub index: u16,
    pub subindex: u8,
    pub data_type: DataType,
    pub access: AccessType,
    pub pdo_mappable: bool,
    pub name: &'static str,
}

/// Errors from OD operations.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum OdError {
    NotFound,
    ReadOnly,
    WriteOnly,
    DataTypeMismatch,
    ValueTooLong,
    ValueRange,
    HardwareError,
}

/// Trait for an object dictionary. Implemented by proc-macro-generated structs.
///
/// All read/write operations use byte slices for transport-level generality.
/// The generated struct provides typed accessor methods for application code.
pub trait ObjectDictionary {
    /// Look up entry metadata by index and subindex.
    fn lookup(&self, index: u16, subindex: u8) -> Option<&'static OdEntryMeta>;

    /// Read a value from the OD into `buf`. Returns the number of bytes written.
    fn read(&self, index: u16, subindex: u8, buf: &mut [u8]) -> Result<usize, OdError>;

    /// Write a value to the OD from `data`.
    fn write(&mut self, index: u16, subindex: u8, data: &[u8]) -> Result<(), OdError>;

    /// Number of subindices for a given index (sub0 value for arrays/records).
    fn sub_count(&self, index: u16) -> Option<u8>;
}
