pub mod client;
pub mod driver;
pub mod protocol;
pub mod server;

pub use client::{SdoClient, SdoClientResult};
pub use driver::{AsyncCan, NbCanAsync, SdoDriver, SdoError};
pub use protocol::AbortCode;
pub use server::SdoServer;

use crate::cobid::NodeId;

/// Resolved parameters of one *additional* SDO server (CiA 301 object
/// 0x1201–0x127F). The default server (0x1200, predefined COB-IDs
/// `0x600/0x580 + node_id`) is always present and not represented here.
///
/// COB-IDs are resolved (node-relative bases already folded against the node
/// id). They are a device design decision fixed at build time — the OD records
/// are read-only and never remappable at runtime. See
/// `_Tasks/additional-sdo-servers.md`.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub struct SdoServerConfig {
    /// CANopen server number (2..=128), i.e. OD record `0x1200 + number - 1`.
    pub number: u16,
    /// COB-ID client→server (request / rx).
    pub cob_rx: u16,
    /// COB-ID server→client (response / tx).
    pub cob_tx: u16,
}

impl SdoServerConfig {
    /// A placeholder used to fill fixed-size arrays; never dispatched (COB-IDs 0
    /// are invalid and match no frame).
    pub const EMPTY: Self = Self {
        number: 0,
        cob_rx: 0,
        cob_tx: 0,
    };
}

/// Source of additional SDO server configuration, implemented by the OD types
/// generated by `object_dictionary!`. [`crate::node::NodeConfig::from_od`] uses
/// it to pull the extra channels' COB-IDs; `SDO` is the number of additional
/// servers declared (0 when none, the default).
pub trait SdoServerConfigSource<const SDO: usize> {
    /// Resolved additional SDO server configs, node-relative COB-IDs folded
    /// against `node_id`.
    fn sdo_server_configs(&self, node_id: NodeId) -> [SdoServerConfig; SDO];
}
